export const TABLES_SCHEMA = [
  {
    id: '5e381797dcb2b80008734826',
    name: 'Users',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'email',
        displayName: 'Email',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'status',
        displayName: 'Status',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'origin',
        displayName: 'Origin',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'is8base',
        displayName: 'Is 8base user',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'firstName',
        displayName: 'First Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'lastName',
        displayName: 'Last Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'timezone',
        displayName: 'Timezone',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'avatar',
        displayName: 'Avatar',
        fieldType: 'FILE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'roles',
        displayName: 'Roles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
      {
        name: 'sentNotifications',
        displayName: 'Sent Notifications',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381adf8caf0200089283b8',
            name: 'Notifications',
          },
        },
      },
      {
        name: 'clientNotifications',
        displayName: 'Client Notifications',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e3a7ca5d8955e00087a44a2',
            name: 'UserNotifications',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b80008734841',
    name: 'Files',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'fileId',
        displayName: 'File ID',
        fieldType: 'UUID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'downloadUrl',
        displayName: 'Download Url',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'shareUrl',
        displayName: 'Share Url',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'provider',
        displayName: 'Provider',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'public',
        displayName: 'Public',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'uploaded',
        displayName: 'Uploaded',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'filename',
        displayName: 'File Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'uploadUrl',
        displayName: 'Upload Url',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'fields',
        displayName: 'Fields',
        fieldType: 'JSON',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'meta',
        displayName: 'Meta',
        fieldType: 'JSON',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'mods',
        displayName: 'Mods',
        fieldType: 'JSON',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'settings_menuBarLogo',
        displayName: 'settings_menuBarLogo',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b8000873486d',
            name: 'Settings',
          },
        },
      },
      {
        name: 'settings_landingPageImage',
        displayName: 'settings_landingPageImage',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b8000873486d',
            name: 'Settings',
          },
        },
      },
      {
        name: 'users_avatar',
        displayName: 'users_avatar',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'teamMembers_avatar',
        displayName: 'teamMembers_avatar',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e38179ddcb2b800087349ec',
            name: 'TeamMembers',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b8000873486d',
    name: 'Settings',
    fields: [
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'passwordMinLength',
        displayName: 'Password Min Length',
        fieldType: 'NUMBER',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'passwordRequireNumbers',
        displayName: 'Password Require Numbers',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'passwordRequireSpecial',
        displayName: 'Password Require Special Symbols',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'passwordRequireUppercase',
        displayName: 'Password Require Uppercase Symbols',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'passwordRequireLowercase',
        displayName: 'Password Require Lowercase Symbols',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'passwordUpdateInterval',
        displayName: 'Password Update Interval',
        fieldType: 'NUMBER',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'rememberDevice',
        displayName: 'Remember Device',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'language',
        displayName: 'Language',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'dateFormat',
        displayName: 'Date Format',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'currency',
        displayName: 'Currency',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'timezone',
        displayName: 'Timezone',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'menuBarLogo',
        displayName: 'Menu Bar Logo',
        fieldType: 'FILE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'landingPageImage',
        displayName: 'Landing Page Image',
        fieldType: 'FILE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'vanityUrl',
        displayName: 'Vanity Url',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'buttonLinkColor',
        displayName: 'Button Link Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'userInterfaceStyle',
        displayName: 'User Interface Style',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'menuBarBGColor',
        displayName: 'Menu Bar Background Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'menuBarIconsColor',
        displayName: 'Menu Bar Icons Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'bgColor',
        displayName: 'Background Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'containerColor',
        displayName: 'Container Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'leftNavColor',
        displayName: 'Left Navigation Color',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
    ],
  },
  {
    id: '5e381797dcb2b800087348c2',
    name: 'Roles',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'name',
        displayName: 'Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'description',
        displayName: 'Description',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'users',
        displayName: 'User',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'permissions',
        displayName: 'Permissions',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348ff',
            name: 'Permissions',
          },
        },
      },
      {
        name: 'apiTokens',
        displayName: 'API Tokens',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b8000873491b',
            name: 'ApiTokens',
          },
        },
      },
      {
        name: 'authenticationProfiles',
        displayName: 'AuthenticationProfiles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e38179adcb2b80008734970',
            name: 'AuthenticationProfiles',
          },
        },
      },
      {
        name: 'teamMembers',
        displayName: 'Team Members',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e38179ddcb2b800087349ec',
            name: 'TeamMembers',
          },
        },
      },
      {
        name: 'notificationTemplates',
        displayName: 'Notification Templates',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381954a399090008810ab5',
            name: 'NotificationTemplates',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b800087348dc',
    name: 'TeamInvitations',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'uuid',
        displayName: 'UUID',
        fieldType: 'UUID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'email',
        displayName: 'Email',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'firstName',
        displayName: 'First Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'lastName',
        displayName: 'Last Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'resentOn',
        displayName: 'Resent On',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'accepted',
        displayName: 'Accepted',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'acceptedOn',
        displayName: 'Accepted On',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'invitee',
        displayName: 'Invitee',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e38179ddcb2b800087349ec',
            name: 'TeamMembers',
          },
        },
      },
      {
        name: 'invitedBy',
        displayName: 'Invited By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e38179ddcb2b800087349ec',
            name: 'TeamMembers',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b800087348ff',
    name: 'Permissions',
    fields: [
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'appId',
        displayName: 'App Id',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'resourceType',
        displayName: 'Resource Type',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'resource',
        displayName: 'Resource',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'permission',
        displayName: 'Permission',
        fieldType: 'JSON',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'role',
        displayName: 'Role',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b8000873491b',
    name: 'ApiTokens',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'name',
        displayName: 'Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'roles',
        displayName: 'Roles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
    ],
  },
  {
    id: '5e381797dcb2b8000873492f',
    name: 'EnvironmentVariables',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'name',
        displayName: 'Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'value',
        displayName: 'Value',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
    ],
  },
  {
    id: '5e38179adcb2b80008734970',
    name: 'AuthenticationProfiles',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'name',
        displayName: 'Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'type',
        displayName: 'type',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'secret',
        displayName: 'Secret',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'managementDomain',
        displayName: 'Management Domain',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'clientId',
        displayName: 'ClientId',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'databaseName',
        displayName: 'Database Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'domain',
        displayName: 'Domain',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'selfSignUpEnabled',
        displayName: 'Is self signUp enabled',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'selfSignUpEmailDomains',
        displayName: 'Self signUp email domains',
        fieldType: 'TEXT',
        isList: true,
        isSystem: true,
        relation: null,
      },
      {
        name: 'roles',
        displayName: 'Roles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
      {
        name: 'audiences',
        displayName: 'audiences',
        fieldType: 'TEXT',
        isList: true,
        isSystem: true,
        relation: null,
      },
    ],
  },
  {
    id: '5e38179adcb2b80008734999',
    name: 'AuthenticationSettings',
    fields: [
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'allowedCallbacks',
        displayName: 'Allowed callbacks',
        fieldType: 'TEXT',
        isList: true,
        isSystem: true,
        relation: null,
      },
      {
        name: 'allowedWebOrigins',
        displayName: 'Allowed web origins',
        fieldType: 'TEXT',
        isList: true,
        isSystem: true,
        relation: null,
      },
      {
        name: 'allowedLogouts',
        displayName: 'Allowed logOuts',
        fieldType: 'TEXT',
        isList: true,
        isSystem: true,
        relation: null,
      },
      {
        name: 'connections',
        displayName: 'Connections',
        fieldType: 'JSON',
        isList: false,
        isSystem: true,
        relation: null,
      },
    ],
  },
  {
    id: '5e38179ddcb2b800087349ec',
    name: 'TeamMembers',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'user',
        displayName: 'User',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'status',
        displayName: 'Status',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'isOwner',
        displayName: 'Is Owner',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'avatar',
        displayName: 'Avatar',
        fieldType: 'FILE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'roles',
        displayName: 'Roles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
      {
        name: 'receivedTeamInvitations',
        displayName: 'Received Team Invitations',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348dc',
            name: 'TeamInvitations',
          },
        },
      },
      {
        name: 'sentTeamInvitations',
        displayName: 'Sent Team Invitations',
        fieldType: 'RELATION',
        isList: true,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348dc',
            name: 'TeamInvitations',
          },
        },
      },
      {
        name: 'email',
        displayName: 'Email',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'firstName',
        displayName: 'First Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'lastName',
        displayName: 'Last Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'timezone',
        displayName: 'Timezone',
        fieldType: 'TEXT',
        isList: false,
        isSystem: true,
        relation: null,
      },
    ],
  },
  {
    id: '5e381954a399090008810ab5',
    name: 'NotificationTemplates',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'name',
        displayName: 'Name',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'description',
        displayName: 'Description',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'title',
        displayName: 'Title',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'message',
        displayName: 'Message',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'entityType',
        displayName: 'Entity Type',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'notifications',
        displayName: 'Notifications',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381adf8caf0200089283b8',
            name: 'Notifications',
          },
        },
      },
      {
        name: 'roles',
        displayName: 'Roles',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381797dcb2b800087348c2',
            name: 'Roles',
          },
        },
      },
    ],
  },
  {
    id: '5e381a36d1978f00089e37ee',
    name: 'Posts',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'title',
        displayName: 'Title',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'message',
        displayName: 'Message',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'notificationEntities',
        displayName: 'Notification Entities',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e3836df9564db0007a4a525',
            name: 'NotificationEntities',
          },
        },
      },
      {
        name: 'hidden',
        displayName: 'Hidden',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'comments',
        displayName: 'Comments',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e396a61be370200087c8743',
            name: 'Comments',
          },
        },
      },
    ],
  },
  {
    id: '5e381adf8caf0200089283b8',
    name: 'Notifications',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'actor',
        displayName: 'Actor',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'template',
        displayName: 'Template',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381954a399090008810ab5',
            name: 'NotificationTemplates',
          },
        },
      },
      {
        name: 'entity',
        displayName: 'Entity',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e3836df9564db0007a4a525',
            name: 'NotificationEntities',
          },
        },
      },
      {
        name: 'clientNotifications',
        displayName: 'Client Notifications',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e3a7ca5d8955e00087a44a2',
            name: 'UserNotifications',
          },
        },
      },
    ],
  },
  {
    id: '5e3836df9564db0007a4a525',
    name: 'NotificationEntities',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'notification',
        displayName: 'Notification',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381adf8caf0200089283b8',
            name: 'Notifications',
          },
        },
      },
      {
        name: 'post',
        displayName: 'Post',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381a36d1978f00089e37ee',
            name: 'Posts',
          },
        },
      },
      {
        name: 'comment',
        displayName: 'Comment',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e396a61be370200087c8743',
            name: 'Comments',
          },
        },
      },
    ],
  },
  {
    id: '5e396a61be370200087c8743',
    name: 'Comments',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'message',
        displayName: 'Message',
        fieldType: 'TEXT',
        isList: false,
        isSystem: false,
        relation: null,
      },
      {
        name: 'post',
        displayName: 'Post',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381a36d1978f00089e37ee',
            name: 'Posts',
          },
        },
      },
      {
        name: 'notificationEntities',
        displayName: 'Notification Entities',
        fieldType: 'RELATION',
        isList: true,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e3836df9564db0007a4a525',
            name: 'NotificationEntities',
          },
        },
      },
    ],
  },
  {
    id: '5e3a7ca5d8955e00087a44a2',
    name: 'UserNotifications',
    fields: [
      {
        name: 'id',
        displayName: 'ID',
        fieldType: 'ID',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdAt',
        displayName: 'Created At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'updatedAt',
        displayName: 'Updated At',
        fieldType: 'DATE',
        isList: false,
        isSystem: true,
        relation: null,
      },
      {
        name: 'createdBy',
        displayName: 'Created By',
        fieldType: 'RELATION',
        isList: false,
        isSystem: true,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'notifier',
        displayName: 'Notifier',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381797dcb2b80008734826',
            name: 'Users',
          },
        },
      },
      {
        name: 'notification',
        displayName: 'Notification',
        fieldType: 'RELATION',
        isList: false,
        isSystem: false,
        relation: {
          refTable: {
            id: '5e381adf8caf0200089283b8',
            name: 'Notifications',
          },
        },
      },
      {
        name: 'read',
        displayName: 'read',
        fieldType: 'SWITCH',
        isList: false,
        isSystem: false,
        relation: null,
      },
    ],
  },
];

export const TABLES_SCHEMA_RESPONSE = {
  system: {
    tablesList: {
      items: TABLES_SCHEMA,
    },
  },
};

export const NOTIFICATIONS_LIST_RESPONSE = {
  userNotificationsList: {
    items: [
      {
        notification: {
          entity: {
            post: {
              id: 'postId',
              createdAt: '2019-10-30T15:05:48.988Z',
              title: 'post title',
              message: 'post message',
            },
          },
          template: {
            key: 'post_created',
            entityType: 'Posts',
            title: 'New post "{{ post.title }}"',
            message: `{{ actor.firstName }} {{ actor.lastName }} created a new post "{{ post.title }}" {{dt "f" post.createdAt }} {{ meta.origin }}`,
            coverImageUrl: '{{{ actor.avatar.downloadUrl }}}',
          },
          actor: {
            id: 'actorId',
            email: 'zouxuoz@gmail.com',
            firstName: 'Vladimir',
            lastName: 'Osipov',
            avatar: {
              id: 'actorAvatarId',
              downloadUrl: 'https://cdn.filestackcontent.com/security=p:policy,s:signature/fileHandle',
            },
          },
        },
        createdAt: '2019-10-30T15:05:48.988Z',
        id: 'notficationId',
        read: false,
      },
    ],
  },
};
